### PR TITLE
Add .net standard support

### PR DESCRIPTION
**Pull request by trurl123**
Also make some properties public to use from custom log aggregator
UPDATE: moved properties fix to another PR

### CODE REVIEW

**Comment by asbjornu** [comment]
This PR tackles a bit more than what was discussed in #195. As far as I can see, only 9e026a584d4c5e46f7727e8fd689eaebd6344ccc seems related to that issue. Would it be possible to have that commit (and related changes) in its own PR, so we can discuss .NET Standard support separately?

**Comment by trurl123** [comment]
I removed commits related to https://github.com/getsentry/raven-csharp/issues/195
So this PR contains only .net standard support

**Comment by beevee** [comment]
Looks like 5 out of 10 open pull requests in this repository are directly related to .NET Core or .NET Standard compatibility. Some of them are open for over a year. I'm worried that this PR will share their fate.

What do you guys (that is, maintainers of this repo) think about .NET Core and .NET Standard? Are there any insurmountable techincal difficulties we don't see?

**Comment by michaeljbaird** [comment]
@trurl123 @asbjornu  I just pulled this PR and tested it out on one of my .Net Core Apps 2.0 and it works as expected. I think the Package task in the `build.cake` script needs a little work as it outputs a Nuget package but does not include icon, description...etc. as before but other than that, it should be ready for nuget.org 👍

**Comment by asbjornu** [comment]
@michaeljbaird: That sounds great! I'll merge this and then we can polish the package metadata in a separate pull request. Are you up for the task? 😃

**Comment by michaeljbaird** [comment]
@asbjornu absolutely.

**Comment by asbjornu** [comment]
@michaeljbaird: Excellent. As the .NET 3.5 support was added rather recently, I don't think we're ready to remove it just yet.

**Pull request merged**
