### PR TITLE
Make Raven more customizable + better C# 6

### PR DESCRIPTION
**Pull request by SPARTAN563**
### Introduction
This pull request adds `async` support and refactors SentryRequest and SentryUser into content classes which use an `ISentryRequestFactory` and `ISentryUserFactory` for fabrication.

### Reasoning
With the introduction of C# 6 happening in the near future (and the subsequent ability to use `await` within `catch` and `finally` blocks) `async` will become far more important to implement.
As for the other stuff, ASP.NET5, OWN/Katana and a variety of other web frameworks don't use `System.Web.HttpContext` - which is currently the only source supported by this library. By refactoring this behaviour out of core classes it becomes far easier for a developer to implement their own generators for this information, as well as permitting them to easily overload specific aspects of the application's behaviour (for example, retrieving additional user information from a database before submitting the report).

### Background
I'm actively in the process of developing an ASP.NET 5 web application to replace an older version which was written on ASP.NET MVC 3. Part of this involves looking for an effective error reporting solution which can easily be adopted throughout the company for their wide range of applications and services (they are in the process of moving away from an existing solution). Demonstrating that Sentry can be used in this situation will go a long way towards easing its adoption within the company.

### CODE REVIEW

**Comment by asbjornu** [comment]
Hey! Sorry for being silent for so long, but I've been swamped. First: Thank you so much for the heap of work you've done here. I'll have a look at it as soon as time allows, which unfortunately isn't today, nor tomorrow. Perhaps next week. Thank you so much for your patience!

**Comment by SPARTAN563** [comment]
Not a problem, the work was conducted to enable support for a system we're developing internally anyway so I figured I'd push the changes upstream in case you wanted them. Obviously no rush in the matter, and I'll see what I can do about publishing my ASP.NET vNext intergration code as well if possible (however it isn't without dependencies, so it will likely work best as a separate package).

**Comment by asbjornu** [comment]
Thanks again, @SPARTAN563. I think this is a good start for a 2.0 version with #65 rolled into it. I merged this in 69674ef0b1681990cca7efc1324687e6b86466fb into the async branch. It would be great if other `async` proponents, like @RealBrubru could have a look at the code and see if it fits the requirements and if this is a good basis for a 2.0 release. It looks good to me.

**Comment by SPARTAN563** [comment]
In reference to ASP.NET vNext integrations - I have managed to open source the module we developed internally which offers an ASP.NET vNext compatible way to handle exceptions within the request pipeline, extract request information within methods in the pipeline and provide it to Raven, as well as offering a set of useful helpers should you wish to extend this.

You'll find the source code at [EMSSConsulting/RavenASP](https://github.com/emssconsulting/RavenASP).

In the interest of decoupling our internal systems from a single service this is built on top of another library called [EMSSConsulting/Auditor](https://github.com/emssconsulting/Auditor) which provides the central logging framework stuff, however were you to package a Raven-ASP.NET vNext integration you would likely bundle these together.

Both are currently undergoing QA testing as part of a larger project within our organization and changes will be pushed as we need them - but feel free to use the code as you wish.

**Comment by asbjornu** [comment]
@SPARTAN563 I've now merged this into `develop`. I haven't made a clear assessment on how backwards compatible `develop` now is with `master`, but if there's no major breaking changes, this will be released as version `1.5` in a not too distant future.

If there's breaking changes, I'll have `develop` in its current state as a basis for version `2.0`, hopefully with #70 or some derivate of it merged in and ready to go.

**Comment by SPARTAN563** [comment]
Thanks, looking forward to seeing it as part of the main package, appreciate the update as well. Obviously, let me know if there's anything which needs changing/fixing closer to the time and I'll see what I can do.

**Comment by asbjornu** [comment]
@SPARTAN563 Thanks for the offer to help. I'll always appreciate more tests or help with any of the outstanding [issues](/getsentry/raven-csharp/issues).

**Comment by stebet** [comment]
Any news on when async support will be released?

**Comment by asbjornu** [comment]
@stebet I'm working on a prerelease package as we speak, actually. But I need help in figuring out why NuGet is unable to make a package from `SharpRaven.Nancy.csproj`. I'm tracking this in #81. Any help would be highly appreciated.

**Comment by stebet** [comment]
Was just about to jump on this when I saw you fixed it :) great job. Any other outstanding issues I can help with?

**Comment by asbjornu** [comment]
@stebet It would be great to get some help testing [SharpRaven.Nancy](https://www.nuget.org/packages/SharpRaven.Nancy) and the new `async` support in [SharpRaven 1.5.1+](https://www.nuget.org/packages/SharpRaven/1.5.1-unstable0134). Report any compatibility problems or other issues you come across here.

**Pull request merged**
