### PR TITLE
BUG: Restore Request.InputStream position after body has been read

### PR DESCRIPTION
**Pull request by brunoblank**
Hi, this is a PR for issue: #209 

Restore the **Request.InputStream.Position** to the position before the body was read.

Regards
Bruno

### CODE REVIEW

**Comment by asbjornu** [comment]
@brunoblank: Thanks for this. Can you please look into why both AppVeyor and Travis is failing the build?

**Comment by brunoblank** [comment]
I have done this bugfix in **master** as I assumed this the released version. The build error and test errors seems to be missing nuget packages / NameResolution error, which my changed *should* not affect.
When I switch to the **develop** branch alot of build realated things as been updated.

Where should the bug-fix be commited?

**Comment by asbjornu** [comment]
@brunoblank: You should preferably create your branch from `develop`. To repurpose your fix onto a branch created from `develop` you can do the following:

```shell
git checkout develop                            # Assumes you have the latest develop from this repository
git checkout -b feature/reset-stream-position   # Creates and checks out a new branch from the HEAD of develop
git cherry-pick --no-edit e246eda               # Cherry-picks your "BUG: Restore Request.InputStream position after body has been read" commit into the feature/reset-stream-position branch
git cherry-pick --no-edit 896a40c               # Cherry-picks your "Added project setting for Net3.5 for SharpRaven.Nancy and SharpRaven" commit into the feature/reset-stream-position branch
git push
```

This will create a new branch from `develop` which you can create a new pull request for. The idea behind having this in a separate branch is so you can make changes in `master` without affecting the pull request.

I'm also not sure about 1e6549b. Has Xbuild been completely phased out?

**Comment by brunoblank** [comment]
Hi, thanks for the separate branch tip.

`896a40c` and `1e6549b` can be ignored as they were added to try to figure out why travis was failing.

New PR #215 has been submitted.

Closing PR

**Pull request closed without merging**
