### PR TITLE
WIP: SharpRaven MEL extension

### LINKED ISSUE #175: Provide an implementation of ILogger from Microsoft.Extensions.Logging
Building on my comment on #125, support for .NET Core, an implementation that fits in `Microsoft.Extensions.Logging` should be provided. I have created my own project for it, copied the same buildup as from the Debug logger, and called it `Microsoft.Extensions.Logging.Raven`, for which I've attached the relevant source code.

Feel free to use the attached as a base to build an "official" log provider for the MS log framework. :)

In the end, the code can be used like this:

	public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
	{
		loggerFactory.AddConsole(Configuration.GetSection("Logging"));
		loggerFactory.AddRavenLogger(app.ApplicationServices.GetRequiredService<IRavenClient>(), LogLevel.Error);
		loggerFactory.AddDebug();
	
		// .. snip
	}

[Microsoft.Extensions.Logging.Raven.zip](https://github.com/getsentry/raven-csharp/files/750639/Microsoft.Extensions.Logging.Raven.zip)

### PR DESCRIPTION
**Pull request by LordMike**
I've updated my code in #175 with some support for scopes and state variables, but I haven't yet mapped those to sentry properties, as I was unsure what goes where.

A short primer on scopes: MEL (Microsoft.Extensions.Logging) has a feature called scopes. You can wrap any piece of code in a `using (myLogger.BeginScope(someValue))`, any log message (f.ex. for SharpRaven) will then include those scopes, in order. This is extremely useful on f.ex. web projects, where ASP.Net by default starts a scope including the RequestId and RequestPath as two properties (a dictionary of string->object) - other code can include their own scopes etc.

Scopes are tricky and widely unsupported, but @nblumhardt has a great blogpost on his interpretation of them [here](https://nblumhardt.com/2016/11/ilogger-beginscope/) - something I can always refer back to :).

Todo:
* [ ] Ensure builds are correct (properties, descriptions, naming, shared properties, cakebuild?, ..)
* [ ] Ensure build works for NET4x
* [ ] Assign State, Scope and others to appropriate Sentry properties
* [ ] Tests

Fixes #175

### CODE REVIEW

**Comment by asbjornu** [comment]
Awesome! I haven't looked thoroughly at either this PR or MEL, but the scopes you're talking about, could they somehow be mapped to [Sentry's breadcrumbs](https://sentry.io/features/breadcrumbs/)?

**Comment by LordMike** [comment]
I believe so. I'm unsure of the order - should Raven get them in outermost-to-innermost in the list (lowest index is outermost) or the other way around? Scopes in MEL are typically implemented as stacks -- the top of the stack is the innermost scope.

They're not breadcrumbs in the strictest sense as they're only as complete as what you specify -- but I suppose this is the intention?

Can I give you access to my repo so you can hook up the builds etc.?

**Comment by asbjornu** [comment]
SharpRaven's breadcrumb implementation supports the notion of "level", so I guess you can increment this for every scope enter and decrement for every scope exit. Representing this with a stack and then just using the stack's length as the level should work fine. Also, the breadcrumb API is very forgiving, so you can omit just about everything and it will still work. Sounds like a great fit to me!

> Can I give you access to my repo so you can hook up the builds etc.?

Not sure why I need that? :)

**Comment by LordMike** [comment]
Heh. I'm not sure how to make this extension work with anything but the latest frameworks (net46 and netstandard2.0 - perhaps netstandard1.6), so "hooking up the build" includes making the build work :)

Right now it's failing with not being able to find a target for net35 -- I'm certain this won't work for net35, ever, as MEL 2.0 only works for netstandard 2.0.

**Comment by asbjornu** [comment]
Just use `#if (!net35)` in `.cs` files and `Condition="'$(TargetFramework)' != 'net35'"` in `.csproj` files for stuff that doesn't work in .NET 3.5. You can find these strewn around the codebase already, so just see how it works and imitate.

**Comment by asbjornu** [comment]
Also, to test the build locally, just run `./build.sh` (on Linux/Unix), `.\build.ps1` in PowerShell or `.\build.cmd` in CMD.

**Comment by asbjornu** [comment]
@LordMike: How's it going with this PR?

**Comment by LordMike** [comment]
Very slow. I'm held up on work and private stuff :/

**Comment by bruno-garcia** [comment]
I hadn't seen this PR but it's exactly what we are trying to accomplish as a first integration on a new API that supports only netstandard2.0:
https://github.com/getsentry/sentry-dotnet/blob/master/samples/Sentry.Samples.ME.Logging/Program.cs

It's a work in progress but soon we'll be able to have ASP.NET Core `AddSentry` with some logging as breadcrumbs. 

I'd love to get your feedback on it. Especially the bits that are accomplishing similar things than this PR: so your experience with it would be very valuable:
https://github.com/getsentry/sentry-dotnet/tree/master/src/Sentry.Extensions.Logging

**Comment by bruno-garcia** [comment]
We've just released the first preview of the `ASP.NET Core` integration. 

It also brings in the `Microsoft.Extensions.Logging` so that your Informational log messages in the same transaction are sent as breadcrumbs.

It's possible to use only the `Microsoft.Extensions.Logging`, without the _ASP.NET Core_ integration.
There's a [sample of it here](https://github.com/getsentry/sentry-dotnet/tree/master/samples/Sentry.Samples.ME.Logging)

I would love to get some feedback as we work toward a point release:

It's on NuGet: 

**Logging integration: https://www.nuget.org/packages/Sentry.Extensions.Logging/**
ASP.NET Core integration: https://www.nuget.org/packages/Sentry.AspNetCore/
Main SDK (client, etc): https://www.nuget.org/packages/Sentry/


Release on GitHub:
https://github.com/getsentry/sentry-dotnet/releases

Docs:
https://github.com/getsentry/sentry-dotnet/

I'm online on Gitter: https://gitter.im/getsentry/dotnet

**Comment by bruno-garcia** [comment]
We've released the new SDK which includes this extension:

https://github.com/getsentry/sentry-dotnet/releases

https://www.nuget.org/packages/Sentry

I'll be happy to help you moving over to the new SDK if some helps is needed. 
Let me know.

**Pull request closed without merging**
