### PR TITLE
Add release support to client

### PR DESCRIPTION
**Pull request by dcramer**
This adds the 'Release' option to RavenClient:

```
cilent.Release = "foobar";
```

Additionally it cleans up some JSON packet logic to make it more testable.

### CODE REVIEW

**Comment by asbjornu** [comment]
This should already be in the develop branch. Please use it as a basis for development. As I've established a GitFlow process for this repository, master is only used as a merge target when doing releases, which makes GitVersion able to version the project easily.

**Comment by dcramer** [comment]
There's no documented guidelines on the repo, and generally if develop is the mainline branch people set it as such (to prevent confusion like this). We can pick and choose the changes, but it might be worthwhile to adopt the standard Sentry contribution practices (even though we dont have them publicly doc'd)

**Comment by dcramer** [comment]
(Also I will go ahead and reoslve conflicts/merge up develop)

**Comment by asbjornu** [comment]
Good point about no documented guidelines. I can add a `CONTRIBUTING.md` file detailing the use of GitFlow, etc. I would have set the `develop` branch as the main branch on GitHub long ago had I had the rights to do so. Alas, I don't. Please feel free to either change my rights on the repository or change it.

If there are `CONTRIBUTING` files in existence for other Sentry projects, I'd love that as a basis for the one for SharpRaven.

**Pull request merged**
