### PR TITLE
Cake build script

### PR DESCRIPTION
**Pull request by will14smith**
I've been following the .NET Core conversation and moving the build system to using Cake seemed to be one of the next steps, so I've given it a go!

### Things I've done:

* Migrated the project files to use the new csproj format. This makes them simpler (useful when you want to hand write conditionals) and gives "easy" access to <TargetFrameworks> which allows multiple framework to be targeted. When I started the idea was this would simplify things, as to whether it did ¯\\_(ツ)_/¯ .

* Removed SharpRaven.WebTest. Migrating this would have been "interesting". Given that it wasn't an automated test and didn't contain any substantial code, I just removed it.

* "Fixed" some tests. The new build scripts seems to run tests slightly differently than the old one did so I had to resolve some issues that came up. Most of it was around Mono, dynamics, and runtime method ambiguities.

* Add the Cake script. It builds all the frameworks, runs tests on all of them, and packages them. Works on AppVeyor (Window), TravisCI (Linux via Mono). The reason it is using AppVeyor is just because I could test different configs more easily. I'm happy to modify the script to work with TeamCity but might some help testing it.

[AppVeyor tests](https://ci.appveyor.com/project/will14smith/raven-csharp/build/2.2.1-cake0010)
[TravisCI tests](https://travis-ci.org/will14smith/raven-csharp/builds/273686551)

I would have liked to have submitted a smaller PR but it's all fairly interconnected (if you would like a smaller PR then I could possibly look into splitting out the project file migration). 

I'm open to feedback, suggestions, changes, etc... 😄

### CODE REVIEW

**Comment by samukce** [comment]
Great work!

**Comment by asbjornu** [comment]
@will14smith: Thanks so much for this! How does this relate to the existing `cake` branch (that also incorporates the `httpclient` branch)? It's great to have AppVeyor support. I would love to ditch the TeamCity build in favour of AppVeyor, but I need administrative rights within the @getsentry organisation to create a project in AppVeyor for it, and I don't. Perhaps pinging @dcramer about it will help? 😃 

I'll move forward with this PR as soon as we get AppVeyor figured out.

**Comment by asbjornu** [comment]
@getsentry/sdks, @HazAT, can you please have a look at my request above?

**Comment by HazAT** [comment]
@asbjornu I will get this rolling, stay tuned.

**Comment by jan-auer** [comment]
@asbjornu The project is created in AppVeyor now: 
https://ci.appveyor.com/project/sentry/raven-csharp

**Comment by asbjornu** [comment]
@jan-auer: Thanks!
@will14smith: Can you please add an `appveyor.yml` to this PR so we can see how the build fares on AppVeyor? When we have that working, I'm going to disable the TeamCity build and merge this.

**Comment by will14smith** [comment]
@asbjornu There already was one :)

I've bumped the last commit to trigger it

**Comment by asbjornu** [comment]
@will14smith: Awesome! AppVeyor went green, but not Travis, unfortunately. 😕

**Comment by will14smith** [comment]
@asbjornu There is a bug in the latest stable release of Mono https://bugzilla.xamarin.com/show_bug.cgi?id=59364

It's fixed in the nightly builds so I've set Travis to use them for now

**Comment by asbjornu** [comment]
@will14smith: I see. Excellent!

**Comment by webchetan** [comment]
Do we have any working package for .net core >= v1.1. I so so want sentry to work for .net core projects. Any help would be great. Thank you!

**Comment by asbjornu** [comment]
@webchetan: No packages yet, as the AppVeyor build mysteriously has stopped working. I'm working to figure it out, though.

**Comment by webchetan** [comment]
@asbjornu Thank you. Package for .NET Core 2.x would be awesome. :)

**Comment by asbjornu** [comment]
@webchetan: As I wrote in #125, [SharpRaven version `2.2.1-unstable0054`](https://www.nuget.org/packages/SharpRaven/2.2.1-unstable0054) was published to NuGet.org yesterday. Please test it and report back your status. Thanks!

**Pull request merged**
