### PR TITLE
Added Seperate Dotnet Core Project

### PR DESCRIPTION
**Pull request by wakawaka54**
Any tests that used the `TestServer` had to be commented out due to no compatibility with core. We can rewrite these tests using `Microsoft.AspNetCore.TestServer`.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-csharp/161)

### CODE REVIEW

**Comment by asbjornu** [comment]
I also need some kind of advice on how to get the project built on [TeamCity](http://teamcity.codebetter.com/viewLog.html?buildId=227954&buildTypeId=bt1000&guest=1).

**Comment by reflectiondm** [comment]
@wakawaka54 I missed that you started the work on creating a separate dotnet Core project so I also have created one here:  #163 . It is already addressing @asbjornu comment regarding files to be linked instead of just coppied. Do you think we can cooperate on it? What's the best way to contact you?

**Comment by wakawaka54** [comment]
@reflectiondm Yes we can! Do you use something I can PM you on and we can talk about the changes and work together?

**Comment by reflectiondm** [comment]
@wakawaka54 I've sent you an email to an email address I found on your profile page.

**Comment by asbjornu** [comment]
I hope #197 gives us the .NET Core / Standard support we need, so I'm closing this. Please `rebase` on `HEAD` of `develop` and reopen if there's something you feel is missing or has room for improvement. Thanks!

**Pull request closed without merging**
