### PR TITLE
Add support for fingerprinting

### PR DESCRIPTION
**Pull request by mattrobenolt**
Fixes GH-72

@asbjornu I'd like to add tests for this, but I have no idea how C# even works or how to run this. :) So some guidance would be helpful if possible.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
It also looks like I need a Team City account to even view the test failure.

/cc @dcramer 

Not sure who can hook me up.

**Comment by dcramer** [comment]
The TC stuff is too complicated to add people to it. We need to make this build on Mono but I haven't had time to give it another try.

**Comment by mattrobenolt** [comment]
Turns out, I can view the results without having an account. :smile: 

But yeah, Travis would be nice. _shrug_

**Comment by asbjornu** [comment]
@dcramer What do you mean with this?

> The TC stuff is too complicated to add people to it. We need to make this build on Mono but I haven't had time to give it another try.

Not having a Windows build on a library that will predominantly be used on Windows is hazardous, imho. 

While I think having a Mono build would be great, [the existing build on TeamCity](http://teamcity.codebetter.com/project.html?projectId=SentryRavenCsharp&tab=projectOverview) is not alien to Windows developers like myself, and should not be replaced with a pure Mono based one. If you need information on how to interpret the build configuration, please ask me, because I'm the one who have made all the latest adjustments to it.

To answer @mattrobenolt's question, adding tests is not any more complicated than adding `public` methods decorated with `[Test]` to an existing test class (found in the [`SharpRaven.UnitTests` assembly](/getsentry/raven-csharp/tree/master/src/tests/SharpRaven.UnitTests)) or a new test class, decorated with `[TestFixture]`. Just looking at some of the existing tests will make this quite self explanatory.

To run the tests locally, you need a test runner. [ReSharper](https://www.jetbrains.com/resharper/) has a good one built in, but in Visual Studio you can download and install others, like the [NUnit Test Adapter](https://visualstudiogallery.msdn.microsoft.com/6ab922d0-21c0-4f06-ab5f-4ecd1fe7175d). If you want to run the tests without Visual Studio altogether, there's a good explanation on how to do that in the [NUnit documentation](http://nunit.org/index.php?p=runningTests&r=2.6.4).

**Comment by dcramer** [comment]
@asbjornu I simply mean that Travis CI is a more approachable quick validation than the TeamCity build

**Comment by mattrobenolt** [comment]
> adding tests is not any more complicated than adding public methods decorated with [Test] to an existing test class (found in the SharpRaven.UnitTests assembly) or a new test class, decorated with [TestFixture]. Just looking at some of the existing tests will make this quite self explanatory.

Is there a way to run on something not Windows? I guess that's where Mono would be nice, but I'm not familiar enough to even know what these words mean.

I'd like to be able to at least sanity check before committing and pushing and letting TC build considering all my mess ups so far were simple compile errors. :)

**Comment by mattrobenolt** [comment]
Also, @asbjornu, if it's not obvious, we really appreciate you maintaining and helping with this since we're generally clueless. :confused:

**Comment by asbjornu** [comment]
@dcramer:
> I simply mean that Travis CI is a more approachable quick validation than the TeamCity build. 

I see. Well, if .NET ran perfectly on all platforms, you could just as well run a command line test runner or script and ignore CI altogether. Unfortunately, it doesn't. At least not yet. [But things are moving in the right direction](http://techcrunch.com/2015/04/29/microsoft-launches-its-net-distribution-for-linux-and-mac/).

> Definitely not suggesting to remove it, just to add more visibility.

Good! Then we agree. :smile: 

@mattrobenolt:
> Is there a way to run on something not Windows?

Not at the moment. #40 was a beginning and I did lot of work to get it up and working on Sentry's Travis server, but after several hours, I just had to give up.

> I guess that's where Mono would be nice, but I'm not familiar enough to even know what these words mean.

Yes, Mono support would help. But you would still need to learn how to write tests for [NUnit](http://nunit.org/).

> I'd like to be able to at least sanity check before committing and pushing and letting TC build considering all my mess ups so far were simple compile errors. :)

Yea, don't we all. :wink: 

> Also, @asbjornu, if it's not obvious, we really appreciate you maintaining and helping with this since we're generally clueless. :confused:

Thanks for that! I think it's fun and Sentry provides us with a lot of value, so it's no problem. I'd love to help out with transferring more knowledge about C# to you guys, though, so please let me know how I can help out in that area! :smile:

**Comment by asbjornu** [comment]
@mattrobenolt Just to get this straight before I merge, the `fingerprint` is basically just an array of strings?

**Comment by mattrobenolt** [comment]
Correct. The key is omitted if nothing is set. 

--
Matt Robenolt
@mattrobenolt




On Wed, Nov 18, 2015 at 6:54 AM -0800, "Asbjørn Ulsberg" <notifications@github.com> wrote:












@mattrobenolt Just to get this straight before I merge, the fingerprint is basically just an array of strings?

**Comment by asbjornu** [comment]
@mattrobenolt Ok, great. Merged to `develop`. I'm not sure when I'll find time to merge to `master` and do a new release, but it hopefully won't be long.

**Pull request closed without merging**
