### PR TITLE
Xamarin.Mac support

### PR DESCRIPTION
**Pull request by mogikanin**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-csharp/145)

### CODE REVIEW

**Comment by asbjornu** [comment]
@mogikanin Thanks for this! But the build fails with the error:

```
SharpRaven.Xamarin.Mac.csproj could not import "$(MSBuildExtensionsPath)\Xamarin\Mac\Xamarin.Mac.CSharp.targets"
```

Think you could look at that?

**Comment by mogikanin** [comment]
This is because it should be opened in Xamarin Studio. or probably in VS with installed xamarin (not sure).

**Comment by asbjornu** [comment]
@mogikanin This has to work on TeamCity and Travis, somehow. Ideas?

**Comment by mogikanin** [comment]
Check this
https://developer.xamarin.com/guides/cross-platform/getting_started/requirements/

As you see, to build xamarin.mac project you need Mac OSX with Xamarin Studio installed.
I think the solution might be:
1. Exclude this project from VS solution.
2. Find a CI which supports Xamarin builds on OSX.

**Comment by asbjornu** [comment]
@mogikanin I see. Travis support [OS X builds](https://docs.travis-ci.com/user/osx-ci-environment/), so we could build that project only on OS X by introducing a [build matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix). See [this](https://docs.travis-ci.com/user/multi-os/) for more information.

**Comment by mogikanin** [comment]
Yes, but they haven't xamarin\C# installed in Compilers and Build toolchain.

**Comment by asbjornu** [comment]
@mogikanin By default, true. But is it not possible to [install](https://docs.travis-ci.com/user/installing-dependencies/)?

**Comment by mogikanin** [comment]
Not sure that will work in case of xamarin. I think you better to ask theirs support about it.

**Comment by asbjornu** [comment]
@mogikanin: Can you perhaps add a `Condition="Exist(...)"` to the `<Import/>` such that `Xamarin.Mac.CSharp.targets` isn't imported if it doesn't exist? This of course needs to be followed up everywhere `Xamarin.Mac.CSharp.targets` is expected to be imported.

**Comment by mogikanin** [comment]
You want this to be able to open project in VS?

**Comment by asbjornu** [comment]
@mogikanin Being able to open this project in Visual Studio and having it build on TeamCity and Travis is a very important feature, yes. :smile:

**Comment by mogikanin** [comment]
maybe then you merge my changes into separate branch, and then do what you want? Or I can give you access to my fork?

**Comment by asbjornu** [comment]
@mogikanin Since I have no personal interest in getting Sentry to work under Xamarin.Mac, I won't spend much time getting this into working order. If you want this merged, it's basically up to you to get the pull request into working order. :smiley:

**Comment by mogikanin** [comment]
I already have working version and it works fine for me. This is why I suggested provide my changes as PR and you agreed with that, but I can't (have no time) fix build, setup CI, etc.

**Comment by dcramer** [comment]
Fwiw I'd love to have Xamarin support but I agree to get it in we'd need it to be stable and maintainable and without some kind of automated validation history tells us it'll be a problem. We don't yet have anyone who's not a volunteer on the C# side so we unfortunately can't help take the patch over.

**Comment by asbjornu** [comment]
Closing due to inactivity.

**Pull request closed without merging**
