### PR TITLE
Async issue on nancy

### PR DESCRIPTION
**Pull request by xpicio**
Hello, i think the async issue is fixed :)

### CODE REVIEW

**Comment by xpicio** [comment]
hello, any news about the nuget package ?

**Comment by asbjornu** [comment]
Sorry, @xpicio, I haven't had time. Can you register a user on [CodeBetter's TeamCity server](http://teamcity.codebetter.com/) and give it a go?

**Comment by xpicio** [comment]
@asbjornu, i can try it. At the moment i did it a new user. The user is xpicio.

**Comment by asbjornu** [comment]
Brilliant. I've given you the "Project Administrator" role of raven-csharp now.

**Pull request merged**
