### PR TITLE
BUG: Restore Request.InputStream position after body has been read

### PR DESCRIPTION
**Pull request by brunoblank**
New PR for #209 based from `develop` branch. Replaces #210

### CODE REVIEW

**Comment by brunoblank** [comment]
Something seems wrong with the travis builds:
```
Unable to load the service index for source https://api.nuget.org/v3/index.json.
  The content at 'https://api.nuget.org/v3/index.json' is not a valid JSON object.
  Unterminated string. Expected delimiter: ". Path 'resources[4].@type', line 26, position 29.
```
Any ideas on how to solve this?

Thanks
/Bruno

**Comment by asbjornu** [comment]
This is indeed very strange. I tried restarting the build, but the error remains. It's also weird that AppVeyor is not initiating a build.

**Comment by brunoblank** [comment]
@asbjornu Any update on this PR? It is blocking us from using Sentry

**Comment by asbjornu** [comment]
Since the failing builds can't be blamed on this code, I'll merge it. We need to figure out the build problems to produce a new package, though.

**Comment by brunoblank** [comment]
Awesome, thanks for looking into this!

**Pull request merged**
